### ISSUE TITLE
upgrade and open

### ISSUE THREAD

**Issue by 1003659191** [Hokkaidosunny/indexdb-api#4]
数据库更新的时候有没有更好的办法解决版本号的问题
目前只能先用open打开然后获取版本号才能更新

**Comment by Hokkaidosunny** [comment]
不是很明白，你期望的效果是什么样的

**Comment by 1003659191** [comment]
export class DatabaseService {
  dbs:{[name:string]:IDBDatabase}={}

  //打开连接
  open(dbName:string):Observable<IDBDatabase>{
    if(this.dbs[dbName])return of(this.dbs[dbName]);
    return new Observable(observer=>{
      let req=indexedDB.open(dbName);
      req.onsuccess=e=>{
        this.dbs[dbName]=req.result;
        observer.next(req.result);
      }
      req.onerror=console.log;
      // req.onupgradeneeded=console.log;
    });
  }
  //升级
  upgrade(dbName:string):Observable<IDBDatabase>{
    return new Observable(observer=>{
      if(this.dbs[dbName]){
        let req=indexedDB.open(dbName,this.dbs[dbName].version+1);
        req.onupgradeneeded=e=>{
          this.dbs[dbName]=req.result;
          observer.next(req.result);
        }
        // req.onsuccess=console.log
        req.onerror=console.log;
      }else{
        this.open(dbName).subscribe(db=>{
          this.dbs[dbName]=db;
          this.upgrade(dbName).subscribe(db=>{
            observer.next(db);
          })
        })
      }
    });
  }
}

有没有一种方法可以在升级版本号的时候不用先连接一遍(因为不知道原先版本号为多少)

**Comment by Hokkaidosunny** [comment]
听起来好像只能将最后一次连接的版本号另外保存起来了（客户端存储或者服务器）

**Comment by 1003659191** [comment]
好吧 暂时只能这样了
